@startuml(id=pipeline)

skinparam componentStyle uml2

' component Strategy

component "Selection Model" as selection
component "Alpha Model" as alpha
component "Rebalance Model" as rebalance
component "Risk Model" as risk
component "Execution Model" as execution

database DB {
    rectangle "Execution Table" as DB_ET
    rectangle "Open Positions" as DB_OP
}
'component DataProvider
'component OrderHandling

selection -d-> alpha : list of tickers
alpha -d-> rebalance : list of tickers + directions
rebalance -d-> risk : list of tickers + direction + amount
risk -d-> execution : execution order

execution .> DB_ET : execution details
DB_ET -u-> DB_OP : update positions
DB_OP .> rebalance : open positions
DB_OP .> risk : open positions



' DataProvider -> selection : historical data
' DataProvider -> alpha : historical data
' DataProvider -> rebalance : historical data
' DataProvider -> risk : historical & realtime data
' DataProvider -> execution : historical & realtime data



'selection <.r. IB : historical data 
'alpha <.r. IB : hist or realtime data
'rebalance <.r. IB : hist data



@enduml