
#ifndef MODELTYPE_H
#define MODELTYPE_H

// ModelType.h
enum class ModelType {
    ROOT,
    ACCOUNT,
    PORTFOLIO,
    STRATEGY,
    STRATEGY_BASIC_TEST,
    STRATEGY_MA,
    STRATEGY_MOMENTUM,
    STRATEGY_SELECTION_MODEL,
    STRATEGY_ALPHA_MODEL,
    STRATEGY_REBALANCE_MODEL,
    STRATEGY_RISK_MODEL,
    STRATEGY_EXECTION_MODEL
};

#endif // MODELTYPE_H
