#ifndef PORTFOLIOMODELDEFINES_H
#define PORTFOLIOMODELDEFINES_H

#define PM_ITEM_ACCOUNT    (0x1000u)
#define PM_ITEM_PARAMETERS (0x2000u)
#define PM_ITEM_PARAMETER  (0x3000u)
#define PM_ITEM_STRATEGIES (0x4000u)
#define PM_ITEM_STRATEGY   (0x5000u)
#define PM_ITEM_PORTFOLIO  (0x6000u)
#define PM_ITEM_ACCOUNTS   (0x7000u)

#define PM_ITEM_ID_MASK    (0xF000u)

#endif // PORTFOLIOMODELDEFINES_H
