#ifndef BACKTEST_MOMENTUME2EUNIVERSE_H
#define BACKTEST_MOMENTUME2EUNIVERSE_H

// Large-cap US equity tickers (Yahoo-style) for multi-symbol momentum / prefetch tests.
// Order is stable; callers typically use .mid(0, N) for an N-name universe.

#include <QStringList>

namespace Backtest {

inline QStringList momentumE2eUniverseSymbols()
{
    return QStringList{
        QStringLiteral("AAPL"),
        QStringLiteral("MSFT"),
        QStringLiteral("NVDA"),
        QStringLiteral("AMZN"),
        QStringLiteral("GOOGL"),
        QStringLiteral("GOOG"),
        QStringLiteral("META"),
        QStringLiteral("TSLA"),
        QStringLiteral("AVGO"),
        QStringLiteral("UNH"),
        QStringLiteral("JPM"),
        QStringLiteral("XOM"),
        QStringLiteral("LLY"),
        QStringLiteral("V"),
        QStringLiteral("MA"),
        QStringLiteral("PG"),
        QStringLiteral("HD"),
        QStringLiteral("MRK"),
        QStringLiteral("COST"),
        QStringLiteral("ABBV"),
        QStringLiteral("KO"),
        QStringLiteral("PEP"),
        QStringLiteral("WMT"),
        QStringLiteral("BAC"),
        QStringLiteral("ORCL"),
        QStringLiteral("CRM"),
        QStringLiteral("ADBE"),
        QStringLiteral("ACN"),
        QStringLiteral("DIS"),
        QStringLiteral("CSCO"),
        QStringLiteral("NFLX"),
        QStringLiteral("AMD"),
        QStringLiteral("TMO"),
        QStringLiteral("LIN"),
        QStringLiteral("DHR"),
        QStringLiteral("TXN"),
        QStringLiteral("QCOM"),
        QStringLiteral("AMGN"),
        QStringLiteral("HON"),
        QStringLiteral("UNP"),
        QStringLiteral("SPGI"),
        QStringLiteral("LOW"),
        QStringLiteral("DE"),
        QStringLiteral("UPS"),
        QStringLiteral("IBM"),
        QStringLiteral("RTX"),
        QStringLiteral("GE"),
        QStringLiteral("CAT"),
        QStringLiteral("BA"),
        QStringLiteral("LMT"),
        QStringLiteral("PM"),
        QStringLiteral("INTC"),
        QStringLiteral("INTU"),
        QStringLiteral("BLK"),
        QStringLiteral("SCHW"),
        QStringLiteral("BK"),
        QStringLiteral("C"),
        QStringLiteral("MS"),
        QStringLiteral("GS"),
        QStringLiteral("AXP"),
        QStringLiteral("AMT"),
        QStringLiteral("CVX"),
        QStringLiteral("PFE"),
        QStringLiteral("ABT"),
        QStringLiteral("BMY"),
        QStringLiteral("CVS"),
        QStringLiteral("CME"),
        QStringLiteral("MCD"),
        QStringLiteral("NKE"),
        QStringLiteral("SBUX"),
        QStringLiteral("MO"),
        QStringLiteral("ELV"),
        QStringLiteral("CI"),
        QStringLiteral("CB"),
        QStringLiteral("PNC"),
        QStringLiteral("PGR"),
        QStringLiteral("MET"),
        QStringLiteral("TRV"),
        QStringLiteral("AIG"),
        QStringLiteral("AFL"),
        QStringLiteral("ALL"),
        QStringLiteral("AON"),
        QStringLiteral("HCA"),
        QStringLiteral("ISRG"),
        QStringLiteral("GILD"),
        QStringLiteral("REGN"),
        QStringLiteral("MDLZ"),
        QStringLiteral("TMUS"),
        QStringLiteral("SO"),
        QStringLiteral("DUK"),
        QStringLiteral("NEE"),
        QStringLiteral("EMR"),
        QStringLiteral("APD"),
        QStringLiteral("ECL"),
        QStringLiteral("ITW"),
        QStringLiteral("PH"),
        QStringLiteral("ETN"),
        QStringLiteral("FDX"),
        QStringLiteral("GD"),
        QStringLiteral("CSX"),
        QStringLiteral("NSC"),
        QStringLiteral("WM"),
        QStringLiteral("RSG"),
        QStringLiteral("ADP"),
        QStringLiteral("ICE"),
        QStringLiteral("MCO"),
        QStringLiteral("SHW"),
        QStringLiteral("SYK"),
        QStringLiteral("TJX"),
        QStringLiteral("TGT"),
        QStringLiteral("ZTS"),
        QStringLiteral("AEP"),
        QStringLiteral("CCI"),
        QStringLiteral("CMCSA"),
        QStringLiteral("PLD"),
        QStringLiteral("EQIX"),
        QStringLiteral("SPG"),
        QStringLiteral("OXY"),
        QStringLiteral("MPC"),
        QStringLiteral("PSX"),
        QStringLiteral("VLO"),
        QStringLiteral("SLB"),
        QStringLiteral("COP"),
        QStringLiteral("EOG"),
        QStringLiteral("FCX"),
    };
}

} // namespace Backtest

#endif
