QT += core testlib sql network gui widgets

TARGET = ibtrading_tests
TEMPLATE = app
CONFIG += c++17 testcase console
CONFIG -= app_bundle

CONFIG(debug, debug|release) {
    DESTDIR     = $$PWD/debug
    OBJECTS_DIR = $$PWD/debug/obj
    MOC_DIR     = $$PWD/debug/moc
    RCC_DIR     = $$PWD/debug/rcc
} else {
    DESTDIR     = $$PWD/release
    OBJECTS_DIR = $$PWD/release/obj
    MOC_DIR     = $$PWD/release/moc
    RCC_DIR     = $$PWD/release/rcc
}

DEFINES += SRCDIR=\\\"$$PWD\\\"

INCLUDEPATH += \
    $$PWD \
    $$PWD/.. \
    $$PWD/../plugins/api \
    $$PWD/../plugins/sdk \
    $$PWD/../Backend \
    $$PWD/../Backtest \
    $$PWD/../Pipeline \
    $$PWD/../Ports \
    $$PWD/../Common \
    $$PWD/../ThirdParty \
    $$PWD/../IBComm \
    $$PWD/../Adapters \
    $$PWD/../Testing \
    $$PWD/../Replay \
    $$PWD/../Blocks \
    $$PWD/../Plugin \
    $$PWD/../Supervision \
    $$PWD/../Logging \
    $$PWD/../Metrics \
    $$PWD/../Strategies/Generic \
    $$PWD/../Strategies/StateMachine \
    $$PWD/../DB \
    $$PWD/../IBComm \
    $$PWD/../CObjects \
    $$PWD/../GeneratedIncludes \
    $$PWD/../SharedUI \
    $$PWD/../StrategyManagementUI \
    $$PWD/../MainSystem \
    $$PWD/../MainSystem/WorkspaceWidgets \
    $$PWD/../Brokers/IB/Shared \
    $$PWD/../ReqManager \
    $$MOC_DIR

unix {
    INCLUDEPATH += $$PWD/../Libs
    LIBS += -L$$PWD/../Libs/ -lbid
    DEPENDPATH += $$PWD/../Libs
    PRE_TARGETDEPS += $$PWD/../Libs/libbid.a
}

win32 {
    LIBS += -L$$PWD/../Libs/win/ -llibbid
    INCLUDEPATH += $$PWD/../Libs/win
    DEPENDPATH += $$PWD/../Libs/win
    PRE_TARGETDEPS += $$PWD/../Libs/win/libbid.lib
}

SOURCES += \
    main.cpp \
    ui/tst_backtest_workspace_coordinator_stubs.cpp \
    data_management/tst_data_management.cpp \
    ../DataManagement/BacktestMarketDataRepository.cpp \
    ../DataManagement/DataSourceIdNormalizer.cpp \
    ../DataManagement/ExportFilenameUtils.cpp \
    ../DataManagement/CsvBarsImporter.cpp \
    ../DataManagement/CsvBarsExporter.cpp \
    ../DataManagement/DataManagementWorker.cpp \
    ../DataManagement/DataManagementService.cpp \
    ../DataManagement/HistoricalBarsCoverageSyncRegistry.cpp \
    ../DataManagement/IBHistoricalBarsCoverageSyncProvider.cpp \
    ../DataManagement/YahooHistoricalBarsCoveragePlanner.cpp \
    ../DataManagement/YahooHistoricalBarsCoverageSyncProvider.cpp \
    db/tst_dbhandler_disconnect.cpp \
    backtest/tst_market_session_utils.cpp \
    blocks/tst_quant_momentum_blocks.cpp \
    backtest/tst_instrument_metadata_resolver.cpp \
    backtest/tst_historical_data_manager_cache.cpp \
    backtest/tst_historical_range_normalizer.cpp \
    backtest/tst_yahoo_universe_validator.cpp \
    backtest/tst_backtest_preflight_coordinator.cpp \
    backtest/tst_workspace_session.cpp \
    backtest/tst_backtest_run_persistence.cpp \
    backtest/tst_backtest_statistics.cpp \
    backtest/tst_backtest_report_golden.cpp \
    backtest/tst_backtest_summary_formatter.cpp \
    ../Brokers/IB/src/Decimal.cpp \
    ../CObjects/caccountsummary.cpp \
    ../CObjects/cposition.cpp \
    ../CObjects/CHistoricalData.cpp \
    ../CObjects/crealtimebar.cpp \
    ../CObjects/cexecutionreport.cpp \
    ../CObjects/ccommissionreport.cpp \
    ../Common/NHelper.cpp \
    ../Common/StorageConfig.cpp \
    ../Common/cprocessingbase_v2.cpp \
    ../IBComm/cbrokerdataprovider.cpp \
    ../CObjects/cdeltaobject.cpp \
    ../CObjects/copenorder.cpp \
    ../CObjects/corderstatus.cpp \
    ../CObjects/coptiontickcomputation.cpp \
    ../CObjects/ctickprice.cpp \
    ../CObjects/cticksize.cpp \
    ../CObjects/ctickgeneric.cpp \
    ../CObjects/ctickstring.cpp \
    ../CObjects/cmktdepth.cpp \
    ../CObjects/cmktdepthl2.cpp \
    ../CObjects/ctickbytickalllast.cpp \
    ../CObjects/chistoricalticks.cpp \
    ../ReqManager/globalreqmanager.cpp \
    ../ReqManager/ReqManager.cpp \
    ../Brokers/IB/src/SoftDollarTier.cpp \
    ../Common/globalsettings.cpp \
    ../Strategies/Generic/cbasemodel.cpp \
    ../Strategies/Generic/cbasicroot.cpp \
    ../Strategies/Generic/cbasicaccount.cpp \
    ../Strategies/Generic/cbasicportfolio.cpp \
    ../Strategies/Generic/cbasicstrategy_V2.cpp \
    ../Strategies/Generic/cbasicselectionmodel.cpp \
    ../Strategies/Generic/cbasicalphamodel.cpp \
    ../Strategies/Generic/cbaserebalancemodel.cpp \
    ../Strategies/Generic/cbasicriskmodel.cpp \
    ../Strategies/Generic/cbasicexecutionmodel.cpp \
    ../Strategies/Generic/cgenericmodelApi.cpp \
    ../Strategies/Generic/cstrategyfactory.cpp \
    ../Strategies/Generic/cpipelinestrategyadapter.cpp \
    ../Strategies/Generic/UnifiedModelData.cpp \
    ../DB/dbhandler.cpp \
    ../DB/dbmanager.cpp \
    ../DB/DBConnector.cpp \
    ../Backend/ModelTreeRepository.cpp \
    ../Backend/ModelTreeRepositoryPostgres.cpp \
    ../Backend/PersistenceFactory.cpp \
    ../Backend/ModelTreeMapper.cpp \
    ../Backend/StrategyLifecycleState.cpp \
    ../Backend/SystemBackendImpl.cpp \
    ../Backtest/SimulatedLedger.cpp \
    ../Backtest/SimulatedExecutionAdapter.cpp \
    ../Backtest/BacktestMetricsCollector.cpp \
    ../Backtest/BacktestStatistics.cpp \
    ../Backtest/BacktestStatisticsCalculator.cpp \
    ../Backtest/HistoricalBarUtils.cpp \
    ../Backtest/BacktestFillValidation.cpp \
    ../Backtest/SemanticMomentumPipeline.cpp \
    ../Backtest/BacktestReportModel.cpp \
    ../Backtest/BacktestReportModelBuilder.cpp \
    ../Backtest/BacktestHtmlTemplateRenderer.cpp \
    ../Backtest/BacktestMetricsMapper.cpp \
    ../Backtest/EquityCurvePnl.cpp \
    ../Backtest/BacktestSummaryFormatter.cpp \
    ../Backtest/Reporting/MomentumSemanticHtmlWriter.cpp \
    ../Backtest/BacktestSession.cpp \
    ../Backtest/BacktestMarketDataAccessor.cpp \
    ../Backtest/BacktestHistoricalReadAdapter.cpp \
    ../Backtest/BacktestWorkspaceSession.cpp \
    ../Backtest/BacktestRunPersistence.cpp \
    ../Backtest/YahooFinanceDataSource.cpp \
    ../Backtest/MarketSessionUtils.cpp \
    ../Backtest/InstrumentClassification.cpp \
    ../Backtest/InstrumentInference.cpp \
    ../Backtest/InstrumentClassificationMappers.cpp \
    ../Backtest/InstrumentNormalization.cpp \
    ../Backtest/InstrumentMetadataResolver.cpp \
    ../Backtest/AssetUniverseInput.cpp \
    ../Backtest/InstrumentMetadataIb.cpp \
    ../Backtest/HistoricalDataManager.cpp \
    ../Backtest/HistoricalRangeNormalizer.cpp \
    ../Backtest/YahooChartBatchFetch.cpp \
    ../Backtest/YahooUniverseValidator.cpp \
    ../Backtest/BacktestPreFlightCoordinator.cpp \
    ../Backtest/BacktestController.cpp \
    ../BacktestUI/BacktestRunConfigPanel.cpp \
    ../MainSystem/WorkspaceWidgets/TradingReadiness.cpp \
    ../SharedUI/StrategyTreeDelegate.cpp \
    ../MainSystem/ciconhandler.cpp \
    ../MainSystem/UiLayoutDefaultsCatalog.cpp \
    ../MainSystem/BacktestWorkspaceCoordinator.cpp \
    ../MainSystem/QtBacktestSessionSwitchPrompt.cpp \
    ../MainSystem/QtUnsavedChangesPrompt.cpp \
    ../SharedUI/AbstractPipelineTreeModel.cpp \
    ../SharedUI/StrategyTreePanel.cpp \
    ../SharedUI/WorkspacePresenterBase.cpp \
    ../SharedUI/StrategyWorkspacePresenter.cpp \
    ../SharedUI/BacktestPresenter.cpp \
    ../SharedUI/PipelineDiagramModel.cpp \
    ../SharedUI/BlockInspectorPresenter.cpp \
    ../SharedUI/StrategyDetailPresenter.cpp \
    ../StrategyManagementUI/StrategyCatalogModel.cpp \
    ../StrategyManagementUI/CatalogTreeModel.cpp \
    ../StrategyManagementUI/StrategyCatalogPanel.cpp \
    ../StrategyManagementUI/StrategyDetailPanel.cpp \
    ../StrategyManagementUI/StrategyManagementPanel.cpp \
    ../Pipeline/PipelineTreeUtils.cpp \
    ../Pipeline/PipelineConfigMutations.cpp \
    ../Pipeline/PipelineLog.cpp \
    ../Pipeline/StrategyPipelineRunner.cpp \
    ../Pipeline/IAlphaBlock.cpp \
    ../Pipeline/IRebalanceBlock.cpp \
    ../Pipeline/IRiskBlock.cpp \
    ../Pipeline/IExecutionBlock.cpp \
    ../Pipeline/SemanticModelDataMapper.cpp \
    ../Pipeline/SemanticPipelineChain.cpp \
    ../Adapters/IBHistoricalDataFetcher.cpp \
    ../Adapters/LiveHistoricalReadAdapter.cpp \
    ../Pipeline/MarketDataCoordinator.cpp \
    ../Pipeline/SubscriptionRequestStore.cpp \
    ../Pipeline/NoOpSubscriptionPort.cpp \
    ../Pipeline/RouterMarketDataAccessor.cpp \
    ../Pipeline/PipelineFactory.cpp \
    ../Pipeline/BlockGraphSerializer.cpp \
    ../Pipeline/UniverseResolver.cpp \
    ../Pipeline/StrategyRuntimePolicy.cpp \
    ../Pipeline/StrategyPipelineRuntimeOptions.cpp \
    ../Pipeline/SignalMergePolicies.cpp \
    ../Pipeline/PipelineExecutionHost.cpp \
    ../Blocks/MomentumAlphaBlock.cpp \
    ../Blocks/MeanReversionAlphaBlock.cpp \
    ../Blocks/MovingAverageCrossoverAlphaBlock.cpp \
    ../Blocks/MaxPositionRiskBlock.cpp \
    ../Blocks/StaticListSelectionBlock.cpp \
    ../Blocks/LimitOrderExecutionBlock.cpp \
    ../Blocks/MarketOrderExecutionBlock.cpp \
    ../Blocks/SimpleRebalanceBlock.cpp \
    ../Blocks/PassAllSelectionBlock.cpp \
    ../Supervision/StrategyRuntime.cpp \
    ../Supervision/Supervisor.cpp \
    ../Plugin/PluginManifest.cpp \
    ../Plugin/ExtensionRegistry.cpp \
    ../Plugin/PluginRuntime.cpp \
    ../Plugin/PluginDataBridge.cpp \
    ../Plugin/PluginWrappers.cpp \
    ../Plugin/PluginLoader.cpp \
    ../IBComm/ProcessingRouterSink.cpp \
    ../MainSystem/WorkspaceWidgets/BlockInspectorPanel.cpp \
    ../MainSystem/WorkspaceWidgets/RuntimePolicyEditor.cpp

HEADERS += \
    ../Pipeline/SemanticPipelineChain.h \
    ../Pipeline/JsonConfigValue.h \
    ../Adapters/IBHistoricalDataFetcher.h \
    ../Adapters/LiveHistoricalReadAdapter.h \
    ../Pipeline/Contracts.h \
    ../Pipeline/IDataSubscriptionPort.h \
    ../Pipeline/SubscriptionRequestStore.h \
    ../Pipeline/NoOpSubscriptionPort.h \
    ../Pipeline/RouterMarketDataAccessor.h \
    ../Pipeline/BlockSubscriptionUtils.h \
    ../Pipeline/Scope.h \
    ../Pipeline/IAlphaBlock.h \
    ../Pipeline/ISelectionBlock.h \
    ../Pipeline/IRebalanceBlock.h \
    ../Pipeline/IRiskBlock.h \
    ../Pipeline/IExecutionBlock.h \
    ../Pipeline/ISignalMergePolicy.h \
    ../Pipeline/SignalMergePolicies.h \
    ../Pipeline/PipelineExecutionHost.h \
    ../IBComm/MarketDataRouter.h \
    ../IBComm/ProcessingRouterSink.h \
    ../Ports/IOrderExecutionPort.h \
    ../Ports/IPositionRepositoryPort.h \
    ../Common/Expected.h \
    ../ThirdParty/expected.hpp \
    ../Adapters/MockExecutionAdapter.h \
    ../Adapters/MockPositionRepository.h \
    ../Testing/MockMarketDataRouter.h \
    ../Testing/IntegrationTestHarness.h \
    ../Replay/MarketDataRecorder.h \
    ../Replay/MarketDataReplayer.h \
    ../Pipeline/BlockRegistry.h \
    ../Pipeline/StrategyPipelineRunner.h \
    ../Pipeline/StrategyRuntimePolicy.h \
    ../Pipeline/StrategyPipelineRuntimeOptions.h \
    ../Pipeline/PipelineDefinition.h \
    ../Pipeline/UniverseResolver.h \
    ../Pipeline/BlockGraphSerializer.h \
    ../Blocks/MomentumAlphaBlock.h \
    ../Blocks/MaxPositionRiskBlock.h \
    ../Blocks/MarketOrderExecutionBlock.h \
    ../Blocks/SimpleRebalanceBlock.h \
    ../Blocks/PassAllSelectionBlock.h \
    ../Blocks/MeanReversionAlphaBlock.h \
    ../Pipeline/PipelineFactory.h \
    ../Plugin/BlockPlugin.h \
    ../Plugin/PluginManifest.h \
    ../Plugin/ExtensionRegistry.h \
    ../Plugin/PluginRuntime.h \
    ../Plugin/PluginDataBridge.h \
    ../Plugin/PluginWrappers.h \
    ../Plugin/PluginLoader.h \
    ../Supervision/BoundedQueue.h \
    ../Supervision/StrategyRuntime.h \
    ../Supervision/Supervisor.h \
    ../Logging/StructuredLogger.h \
    ../Metrics/MetricsCollector.h \
    ../Strategies/Generic/ModelType.h \
    ../Backend/StrategyLifecycleState.h \
    phase1/tst_contracts.h \
    phase1/tst_merge_policies.h \
    phase1/tst_market_data_router.h \
    phase1/tst_block_interfaces.h \
    phase1/tst_expected.h \
    phase1/tst_scope.h \
    phase1/tst_subscription_request_store.h \
    phase2/tst_replay.h \
    phase2/tst_adapters.h \
    phase2/tst_integration.h \
    phase3/tst_block_registry.h \
    plugin/tst_plugin_runtime.h \
    phase3/tst_pipeline_runner.h \
    phase3/tst_semantic_mapping.h \
    phase4/tst_supervision.h \
    phase5/tst_observability.h \
    phase6/tst_benchmark.h \
    integration/tst_default_pipelines.h \
    integration/tst_pipeline_strategy_adapter.h \
    integration/tst_live_execution_wiring.h \
    integration/tst_typed_routers.h \
    integration/tst_phase_b_migration.h \
    integration/tst_phase_d_dispatcher_removal.h \
    integration/tst_phase_e_remaining_routers.h \
    ../Adapters/IBOrderExecutionAdapter.h \
    ../Adapters/IBPositionRepositoryAdapter.h \
    ../Adapters/SqlitePositionRepository.h \
    ../Blocks/StaticListSelectionBlock.h \
    ../Blocks/LimitOrderExecutionBlock.h \
    ../Blocks/MovingAverageCrossoverAlphaBlock.h \
    ../IBComm/IBrokerAPI.h \
    ../IBComm/PositionRouter.h \
    ../IBComm/HistoricalDataRouter.h \
    ../IBComm/OrderRouter.h \
    ../IBComm/AccountRouter.h \
    ../IBComm/TimeRouter.h \
    ../IBComm/MarketDepthRouter.h \
    ../CObjects/caccountsummary.h \
    ../CObjects/cposition.h \
    ../CObjects/CHistoricalData.h \
    ../CObjects/crealtimebar.h \
    ../CObjects/cexecutionreport.h \
    ../CObjects/ccommissionreport.h \
    ../Common/IClock.h \
    ../Backtest/BacktestConfig.h \
    ../Backtest/BacktestResult.h \
    ../Backtest/DataQuality.h \
    ../Backtest/FilledOrder.h \
    ../Backtest/LedgerSnapshot.h \
    ../Backtest/MarketPriceStore.h \
    ../Backtest/SimulatedLedger.h \
    ../Backtest/SimulatedExecutionAdapter.h \
    ../Backtest/BacktestMetricsCollector.h \
    ../Backtest/IHistoricalDataSource.h \
    ../Backtest/JsonlHistoricalDataSource.h \
    ../Backtest/CsvHistoricalDataSource.h \
    ../Backtest/YahooFinanceDataSource.h \
    ../Backtest/BenchmarkComparison.h \
    ../Backtest/BacktestReportWriter.h \
    ../Backtest/BacktestSession.h \
    ../Backtest/BacktestMarketDataAccessor.h \
    ../Backtest/BacktestHistoricalReadAdapter.h \
    ../Backtest/BacktestController.h \
    ../BacktestUI/BacktestWorkspaceDock.h \
    ../BacktestUI/BacktestRunConfigPanel.h \
    ../MainSystem/WorkspaceWidgets/TradingReadiness.h \
    ../BacktestUI/BacktestStrategySelector.h \
    ../Backtest/BacktestPreFlightCoordinator.h \
    ../Backtest/MarketSessionUtils.h \
    ../Backtest/InstrumentClassification.h \
    ../Backtest/InstrumentInference.h \
    ../Backtest/InstrumentClassificationMappers.h \
    ../Backtest/InstrumentNormalization.h \
    ../Backtest/InstrumentMetadataResolver.h \
    ../Backtest/AssetUniverseInput.h \
    ../Backtest/InstrumentMetadataIb.h \
    ../Backtest/HistoricalDataManager.h \
    ../Backtest/HistoricalRangeNormalizer.h \
    ../Backtest/YahooChartBatchFetch.h \
    backtest/tst_backtest.h \
    backtest/tst_yahoo_backtest.h \
    backtest/tst_momentum_three_stock_validation.h \
    backtest/tst_momentum_hundred_stock_validation.h \
    backtest/momentum_e2e_universe.h \
    backtest/tst_market_session_utils.h \
    blocks/tst_quant_momentum_blocks.h \
    backtest/tst_instrument_metadata_resolver.h \
    backtest/tst_historical_data_manager_cache.h \
    backtest/tst_historical_range_normalizer.h \
    backtest/tst_yahoo_universe_validator.h \
    backtest/tst_backtest_preflight_coordinator.h \
    data_management/tst_data_management.h \
    ../DataManagement/DataManagementWorker.h \
    ../DataManagement/DataManagementService.h \
    ../DataManagement/IBHistoricalBarsCoverageSyncProvider.h \
    backtest/tst_backtest_extended.h \
    backtest/tst_live_backtest.h \
    backtest/tst_backtest_engine_coverage.h \
    backtest/tst_workspace_session.h \
    backtest/tst_backtest_run_persistence.h \
    backtest/tst_backtest_statistics.h \
    backtest/tst_backtest_report_golden.h \
    backtest/tst_backtest_summary_formatter.h \
    db/tst_dbhandler_disconnect.h \
    backend/tst_storage_config.h \
    backend/tst_persistence_factory.h \
    backend/tst_model_tree_repository.h \
    backend/tst_system_backend.h \
    backend/tst_persistence.h \
    backend/tst_runtime.h \
    backend/tst_cli_proof.h \
    backend/tst_strategy_definition.h \
    backend/tst_strategy_catalog.h \
    pipeline/tst_pipeline_config_mutations.h \
    integration/tst_adapter_pure_backtest.h \
    integration/tst_semantic_e2e.h \
    parity/tst_pipeline_parity.h \
    ../Backend/ISystemBackend.h \
    ../MainSystem/BacktestWorkspaceCoordinator.h \
    ../MainSystem/IBacktestSessionSwitchPrompt.h \
    ../MainSystem/IUnsavedChangesPrompt.h \
    ../Backend/SystemBackendImpl.h \
    ../Backend/ModelNodeRecord.h \
    ../Backend/IModelTreeRepository.h \
    ../Backend/ModelTreeRepository.h \
    ../Backend/ModelTreeRepositoryPostgres.h \
    ../Backend/PersistenceFactory.h \
    ../Backend/ModelTreeMapper.h \
    ../Strategies/Generic/cbasemodel.h \
    ../Strategies/Generic/cbasicroot.h \
    ../Strategies/Generic/cbasicaccount.h \
    ../Strategies/Generic/cbasicportfolio.h \
    ../Strategies/Generic/cbasicstrategy_V2.h \
    ../Strategies/Generic/cbasicselectionmodel.h \
    ../Strategies/Generic/cbasicalphamodel.h \
    ../Strategies/Generic/cbaserebalancemodel.h \
    ../Strategies/Generic/cbasicriskmodel.h \
    ../Strategies/Generic/cbasicexecutionmodel.h \
    ../Strategies/Generic/cstrategyfactory.h \
    ../Strategies/Generic/cpipelinestrategyadapter.h \
    ../Strategies/Generic/UnifiedModelData.h \
    ../Strategies/Generic/IMandatoryFields.h \
    ../Strategies/Generic/mandatoryFieldKeys.h \
    ../Strategies/Generic/mandatoryFieldRegistration.h \
    ../Strategies/Generic/modelConstants.h \
    ../Strategies/StateMachine/cmodelstate.h \
    ../Strategies/StateMachine/cmodelstateimpl.h \
    ui/tst_backtest_workspace_coordinator.h \
    ../Strategies/StateMachine/ModelStateUtils.h \
    ../Common/cprocessingbase_v2.h \
    ../DB/dbhandler.h \
    ../DB/dbmanager.h \
    ../DB/dbdatatypes.h \
    ../DB/DBConnector.h \
    ../CObjects/cdeltaobject.h \
    ../CObjects/copenorder.h \
    ../CObjects/corderstatus.h \
    ../CObjects/coptiontickcomputation.h \
    ../CObjects/ctickprice.h \
    ../CObjects/cticksize.h \
    ../CObjects/ctickgeneric.h \
    ../CObjects/ctickstring.h \
    ../CObjects/cmktdepth.h \
    ../CObjects/cmktdepthl2.h \
    ../CObjects/ctickbytickalllast.h \
    ../CObjects/chistoricalticks.h \
    ../IBComm/cbrokerdataprovider.h \
    ../Common/globalsettings.h \
    ../ReqManager/globalreqmanager.h \
    ../ReqManager/ReqManager.h \
    ../SharedUI/StrategyTreeDelegate.h \
    ../SharedUI/AbstractPipelineTreeModel.h \
    ../SharedUI/StrategyTreePanel.h \
    ../SharedUI/ViewModels.h \
    ../SharedUI/IWorkspaceView.h \
    ../SharedUI/WorkspacePresenterBase.h \
    ../SharedUI/StrategyWorkspacePresenter.h \
    ../SharedUI/BacktestPresenter.h \
    ../SharedUI/PipelineDiagramModel.h \
    ../SharedUI/BlockInspectorPresenter.h \
    ../SharedUI/StrategyDetailPresenter.h \
    ../StrategyManagementUI/StrategyCatalogModel.h \
    ../StrategyManagementUI/CatalogTreeModel.h \
    ../StrategyManagementUI/StrategyCatalogPanel.h \
    ../StrategyManagementUI/StrategyDetailPanel.h \
    ../StrategyManagementUI/StrategyManagementPanel.h \
    ../Pipeline/PipelineTreeUtils.h \
    ../Pipeline/PipelineConfigMutations.h \
    ../Pipeline/PipelineLog.h \
    ../MainSystem/WorkspaceWidgets/BlockInspectorPanel.h \
    ../MainSystem/WorkspaceWidgets/RuntimePolicyEditor.h \
    ui/tst_runtime_policy_editor.h \
    ui/tst_trading_readiness.h
